version: "3.9"

services:
  create_nestjs_app:
    build:
      dockerfile: Dockerfile
      context: ./
    restart: on-failure
    volumes:
      - .:/project
    expose:
      - "3000"
    ports:
      - "3000:3000"
